name: credit_scoring          # â† nom libre, sans espace
channels:
  - conda-forge               # toujours en premier pour plus de paquets
dependencies:
  - python=3.12.3             # ğŸ”’ version Ã©pinglÃ©e
  - pip                       # ajoute pip Ã  lâ€™environnement
  - pip:
      - -r requirements.txt   # rÃ©utilise ton requirements.txt existant
